version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(maint)"
    target-branch: "develop"
    ignore:
      - dependency-name: "Cake.Core"
      - dependency-name: "Cake.Common"
      - dependency-name: "Cake.Testing"
    labels: [ ]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "(maint)"
    target-branch: "develop"
    labels: [ "Build" ]