name: Build

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2025, ubuntu-24.04, macos-15 ]

    env:
      AZURE_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
      AZURE_SOURCE: ${{ secrets.AZURE_SOURCE }}
      AZURE_USER: ${{ secrets.AZURE_USER }}
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      GITTER_ROOM_ID: ${{ secrets.GITTER_ROOM_ID }}
      GPR_PASSWORD: ${{ secrets.GPR_PASSWORD }}
      GPR_SOURCE: ${{ secrets.GPR_SOURCE }}
      GPR_USER: ${{ secrets.GPR_USER }}
      GITTER_TOKEN: ${{ secrets.GITTER_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: "https://api.nuget.org/v3/index.json"
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      WYAM_ACCESS_TOKEN: ${{ secrets.WYAM_ACCESS_TOKEN }}
      WYAM_DEPLOY_BRANCH: "gh-pages"
      WYAM_DEPLOY_REMOTE: ${{ github.event.repository.html_url }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x
            7.0.x

      - name: Install mono
        if: runner.os == 'Linux'
        # check https://www.mono-project.com/download/stable/#download-lin
        run: |
            sudo apt install ca-certificates gnupg
            sudo gpg --homedir /tmp --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/mono-official-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            sudo chmod +r /usr/share/keyrings/mono-official-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/mono-official-archive-keyring.gpg] https://download.mono-project.com/repo/ubuntu stable-focal main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
            sudo apt update
            sudo apt install -y mono-complete
            mono --version

      - name: Cache Tools
        uses: actions/cache@v3
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}

      - name: Build project
        uses: cake-build/cake-action@v1
        with:
          script-path: recipe.cake
          target: CI
          verbosity: Normal
          cake-version: tool-manifest

      - name: Upload Issues-Report
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: warn
          name: issues
          path: BuildArtifacts/report.html

      - name: Upload Packages
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*